### PR TITLE
Update of language files

### PR DESCRIPTION
**Pull request by damircalusic**
Fixed missing translation and synced proper pot file

### CODE REVIEW

**Comment by yratof** [comment]
You should compile the translations from within the plugin, as the .po shows `../../../../../shared/wp-content/plugins/` for all refs

**Comment by damircalusic** [comment]
Ah sorry for that @yratof did not realize that!

**Comment by damircalusic** [comment]
@yratof I have fixed proper pathing and fix the pot file to latest. Please review.

**Review by yratof — APPROVED** [review]

**Review by yratof — APPROVED** [review]

**Review by yratof — APPROVED** [review]

**Review by yratof — APPROVED** [review]

**Review by forsvunnet — APPROVED** [review]
Some of the translations need to be changed. I'll approve these changes for now and review translations before publishing the next version

**Comment by forsvunnet** [comment]
@damircalusic Your pull request was against master which is not the active development version. I changed the target branch to develop, but there are now conflicts that must be resolved before we can merge this PR.

**Pull request closed without merging**
